FROM node:18-alpine

WORKDIR /app

ENV NPM_CONFIG_CACHE=/app/.npm

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]

